### ISSUE TITLE
DevicePlugin Manual for Android Studioでのサンプル動作確認について

### ISSUE THREAD

**Issue by todayandroid** [DeviceConnect/DeviceConnect-Android#167]
※申し訳ございません。
　直前に誤って質問を作成してしまったため、「closed」として改めて質問させていただきます。

現在、以下のwikiに記載された手順に沿ってAndroidでのプラグインの作成を進めております。
"https://github.com/deviceconnect/DeviceConnect-Android/wiki/DevicePlugin-Manual-for-Android-Studio"

途中「 7.4 RESTfulでの確認 」の中で、serviceinformationの取得に以下のエラーで失敗しております。

○リクエスト
※Windwsよりcmdを使用してリクエストを送信
curl http://192.168.xxx.xxx:4035/gotapi/serviceinformation?serviceId=(serviceId)
○レスポンス
{"result":1,"product":"Device Web API Manager","errorCode":1,"version":"1.0.8","errorMessage":"Unable to find explicit activity class {com.mycompany.devicepluginsample1\/org.deviceconnect.android.localoauth.activity.ConfirmAuthActivity}; have you declared this activity in your AndroidManifest.xml?"}
○使用端末
・Galaxy J(Android 5.0)

サンプルの手順内に、認証用画面の実装については記載がないのですが、追加での実装などが必要でしょうか。
#指定しているActivityへのパスが怪しいと感じております。。。

お手数ですが、ご回答の程よろしくお願いいたします。

**Comment by Onuzimoyr** [comment]
@todayandroid 様
ご連絡を頂きました内容から、プラグイン開発に要するSDKが、参照できていないのかも知れません。
お手数ですが、wiki に記載の以下2つを、開発環境にダウンロード頂き、個別に手動で設定頂くことは可能でしょうか？
> https://raw.githubusercontent.com/DeviceConnect/DeviceConnect-Android/master/dConnectSDK/dConnectSDKForAndroid/repository/
> https://raw.githubusercontent.com/DeviceConnect/DeviceConnect-Android/master/dConnectDevicePlugin/dConnectDevicePluginSDK/repository/
> 

> サンプルの手順内に、認証用画面の実装については記載がないのですが、追加での実装などが必要でしょうか。
認証用画面については、再利用可能なものがプラグイン用SDK（dConnectDevicePluginSDK）にありますので、個別に新しく追加実装頂くことはありません。

**Comment by todayandroid** [comment]
@Onuzimoyr 様
ご連絡いただき、誠にありがとうございます。

ご指摘いただいた内容にて対応(ダウンロード、ローカルファイルへの参照の追加)を行い、認証画面が表示されることを確認いたしました。
お忙しい中ご連絡いただき、ありがとうございました。
