### ISSUE TITLE
SSL通信について

### ISSUE THREAD

**Issue by kiyohito-nagano** [DeviceConnect/DeviceConnect-Android#267]
現在DeviceConnectを利用してWebRTCを行う通信のシステムを検討しております。
UIをブラウザで行うようにしたいのでDeviceConnectをシステムに組み込む形で検討しています。

HTTPSのサーバでjavascriptを動作させてDeviceConnectを利用する方針で進めています。
その際にDeviceConnectのプラグインへのアクセスがhttp://localhost のため、HTTPSとHTTPが混在していることが原因でエラーになってしまいます。(HTTP環境下では正しく動作しております)

- セキュアな環境下でDeviceConnectを利用することはできますでしょうか？
- HTTPSを利用した場合に、どのようにDeviceConnectを利用するのが適切でしょうか？
単純にhttps://localhost とした場合にはDeviceConnectとの接続でエラーになりました。

システムへの組み込みを考えた場合に、HTTPSを使った通信ができない場合にはシステム構成を再検討する必要があると考えてます。
現状がHTTPS環境で動作しない場合に、HTTPS環境下で動作させるためのアップデートなどはご検討されていますでしょうか？
それとも、今後も未サポートまたは、混在ブロックの解除などの別の手法で回避することを想定していますでしょうか？

ブラウザやその他アプリのバージョンは下記で確認しています。
- Chrome : 56.0.2924.87 
- Firefox : 52.0.1
- Device Web API Manager : 2.0.6
- Android : Nexus6
- Android Version : 5.1

**Comment by Onuzimoyr** [comment]
ご質問頂きました件、以下回答致します。

> セキュアな環境下でDeviceConnectを利用することはできるか？

現在、デバイスコネクトを使ったセキュア通信には、自己署名の証明書を使用しており、ブラウザからアクセスする場合、以下のような動きとなります。
・Chrome：自己署名証明書を発行しているWebサーバのページを開き、ユーザ許可した後、Webアプリ⇔Webサーバ間で通信が可能
・Firefox：Webアプリ⇔Webサーバ間での通信不可

大変お手数をお掛け致しますが、現時点では、構成の再度のご検討を頂けましたら幸いです。

> HTTPS環境下で動作させるためのアップデートなどは検討しているか？
> それとも、今後も未サポートまたは、混在ブロックの解除などの別の手法で回避することを想定しているか？

将来は、HTTPS環境下でも動作するようにしたいと考えますが、対応予定時期などは、現時点では申し上げられない状況です。

申し訳ありませんが、上記ご了解頂けましたら幸いです。

**Comment by kiyohito-nagano** [comment]
ご連絡ありがとうございます。
動作の状況理解しました。
