### ISSUE TITLE
UVC Plugin Crashing Problem

### ISSUE THREAD

**Issue by kim00kim** [DeviceConnect/DeviceConnect-Android#311]
Good day!
 
I have encountered a problem while using the Device Connect Manager.

Based on instruction here https://github.com/DeviceConnect/DeviceConnect-Android/wiki/UVC-Build, we have build and installed UVC plugin in our device.
However, everytime we click "Search Services", a pop up error is being displayed: "Unfortunately, UVC (Device Connect Device Plugin) has stopped".

In Settings->List of device plug-in->UVC (Device Connect Device Plugin)->Open settings->we clicked Add, then we tried to connect to the uvc device (webcam) manually.
But, it takes too long to process. And when the device gets to sleep mode, the process just stops.

I would like to know if you have encountered such issue and what shall we do to resolve this.

Thank you very much.

![dcm_connecting](https://user-images.githubusercontent.com/9582956/28448436-a42991da-6e0a-11e7-92a7-189b97cfd88b.png)
![dcm_crashed](https://user-images.githubusercontent.com/9582956/28448437-a43cc462-6e0a-11e7-97be-5dbf0d98fbdd.png)

**Comment by Onuzimoyr** [comment]
@kim00kim We are afraid but haven't seen such issues so far, would like to have some info as following.
1. what model and its Android Version you use?
2. can we have the model name or number of the webcam if possible?
3. for reference, can we know how much time does it take of "too long to process"?

Besides, if you are making an app, we would suggest you to once use the apk which was already released below;
https://github.com/DeviceConnectUsers/deviceconnectusers.github.io/releases/download/v2.2.4-release-20170623-Android/dConnectDeviceUVC.apk

** We have opened the community space of Device WebAPI as below.
https://github.com/deviceconnectusers/community

If you have something to question or share, we would welcome you to put any massages.
Thank you.

**Comment by kim00kim** [comment]
@Onuzimoyr Thank you for your reply.

1. For the device we use:
    * Acer Iconia Talk 7, Android v5.1
    * Asus Zenfone 2 ZE551ML, Android v6.0.1
2. For the webcam we use:
    * Logicool c920
    * Logicool Orbit/Sphere

Update:
** For Acer Iconia Talk 7:
We tried the apk you have given and tested it on one of our device (Acer Iconia Talk 7) and it is working compared to the apk we build (not sure what the problem is).
When we tried to send request on GET /gotapi/mediaStreamRecording/mediaRecorder, the application still crashes. 
Is it possible that the issue is the device does not have enough power to supply the webcam? Or might be other cause?

I attached screenshots from Acer Iconia Talk 7
![connected](https://user-images.githubusercontent.com/9582956/28555475-cb711e86-7132-11e7-9876-f1db847804cc.png)
![request_crashed](https://user-images.githubusercontent.com/9582956/28555481-d18ecdfe-7132-11e7-88cd-cffd738f03e5.png)
![missing](https://user-images.githubusercontent.com/9582956/28555485-d360128c-7132-11e7-93e6-494aa18a6379.png)

** For Asus Zenfone 2:
We still cannot run properly the apk you gave on the other device (Asus Zenfone 2). The application still crashes when trying to connect the device in Settings->List of device plug-in->UVC (Device Connect Device Plugin)->Open settings-> Add -> Connect.

If you have any questions, please leave a reply.
Thank you very much.

**Comment by Onuzimoyr** [comment]
@kim00kim Thank you for more details.
We have also reproduced with the device, now fixing. The revised will be released around next week.

Besides we would like to have your logcat when this error happened so that check if there are any other causes or not.

** FYI **
If you built the plugin with NDK15, an exception might be happened while operating.
https://github.com/saki4510t/UVCCamera/issues/181

**Comment by kim00kim** [comment]
Thank you again for your reply.

I reproduced again the said problem and I saw this on the logs:

```
08-01 18:19:08.968 D/SensorService( 747): SensorService hasOneShotSensors handle:1 mode:0
08-01 18:19:08.976 E/AndroidRuntime(17276): FATAL EXCEPTION: pool-3-thread-1
08-01 18:19:08.976 E/AndroidRuntime(17276): Process: org.deviceconnect.anrdroid.deviceplugin.uvc, PID: 17276
08-01 18:19:08.976 E/AndroidRuntime(17276): java.lang.NullPointerException: Attempt to invoke virtual method 'int org.deviceconnect.android.deviceplugin.uvc.core.UVCDevice$PreviewOption.getWidth()' on a null object reference
08-01 18:19:08.976 E/AndroidRuntime(17276): at org.deviceconnect.android.deviceplugin.uvc.core.UVCDevice.getPreviewWidth(UVCDevice.java:415)
08-01 18:19:08.976 E/AndroidRuntime(17276): at org.deviceconnect.android.deviceplugin.uvc.profile.UVCMediaStreamRecordingProfile.setMediaRecorder(UVCMediaStreamRecordingProfile.java:365)
08-01 18:19:08.976 E/AndroidRuntime(17276): at org.deviceconnect.android.deviceplugin.uvc.profile.UVCMediaStreamRecordingProfile.setMediaRecorders(UVCMediaStreamRecordingProfile.java:355)
08-01 18:19:08.976 E/AndroidRuntime(17276): at org.deviceconnect.android.deviceplugin.uvc.profile.UVCMediaStreamRecordingProfile.access$500(UVCMediaStreamRecordingProfile.java:42)
08-01 18:19:08.976 E/AndroidRuntime(17276): at org.deviceconnect.android.deviceplugin.uvc.profile.UVCMediaStreamRecordingProfile$3$1.run(UVCMediaStreamRecordingProfile.java:125)
08-01 18:19:08.976 E/AndroidRuntime(17276): at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
08-01 18:19:08.976 E/AndroidRuntime(17276): at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
08-01 18:19:08.976 E/AndroidRuntime(17276): at java.lang.Thread.run(Thread.java:818)

08-01 18:19:09.010 I/BufferQueue( 225): [unnamed-225-665](this:0xb7a15c68,id:665,api:0,p:-1,c:-1) BufferQueue core=(225:/system/bin/surfaceflinger)
08-01 18:19:09.011 I/BufferQueueConsumer( 225): [unnamed-225-665](this:0xb7a15c68,id:665,api:0,p:-1,c:225) connect(C): consumer=(225:/system/bin/surfaceflinger) controlledByApp=false
08-01 18:19:09.011 I/BufferQueueConsumer( 225): [unnamed-225-665](this:0xb7a15c68,id:665,api:0,p:-1,c:225) setConsumerName: unnamed-225-665
08-01 18:19:09.011 I/BufferQueueConsumer( 225): [Application Error: org.deviceconnect.anrdroid.deviceplugin.uvc](this:0xb7a15c68,id:665,api:0,p:-1,c:225) setConsumerName: Application Error: org.deviceconnect.anrdroid.deviceplugin.uvc
08-01 18:19:09.011 I/BufferQueueConsumer( 225): [Application Error: org.deviceconnect.anrdroid.deviceplugin.uvc](this:0xb7a15c68,id:665,api:0,p:-1,c:225) setDefaultBufferSize: width=65 height=65

08-01 18:19:10.750 I/BufferQueueProducer( 225): [Application Error: org.deviceconnect.anrdroid.deviceplugin.uvc](this:0xb7a15c68,id:665,api:1,p:-1,c:225) disconnect(P): api 1
08-01 18:19:10.750 I/BufferQueueConsumer( 225): [Application Error: org.deviceconnect.anrdroid.deviceplugin.uvc](this:0xb7a15c68,id:665,api:1,p:-1,c:225) getReleasedBuffers: returning mask 0xfffffffffffffffb
```
Would this information be enough already?

> ** FYI **
If you built the plugin with NDK15, an exception might be happened while operating.
saki4510t/UVCCamera#181

By the way, thank you for this. Will try this later on.

Thank you very much again for looking into this.

**Comment by Onuzimoyr** [comment]
@kim00kim The fixed was pull-requested on https://github.com/DeviceConnect/DeviceConnect-Android/issues/313. You can pull or download this repository, and try to check build and behavior again.

Once close this issue. If any issues you have, please reopen here or open another ticket.
